development:
  adapter: mysql2
  database: waker_development
  encoding: utf8mb4

test:
  adapter: mysql2
  database: waker_test
  encoding: utf8mb4

production:
  adapter: mysql2
  database: <%= ENV['RAILS_DATABASE_NAME'] || 'example' %>
  username: <%= ENV['RAILS_DATABASE_USERNAME'] || 'example' %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] || 'example' %>
  host: <%= ENV['RAILS_DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || '3306' %>
  encoding: utf8
